version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID    : "484907488753"
    
# phases:
#   install:
#     runtime-versions:
#       docker: 18
phases:
  install:
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version 
  
  build:
    commands:
      - echo Build started on `date`
      - docker build -t my-nodejs-app .
      - docker images
  post_build:
    commands:
      - echo Build completed on `date`
      - docker tag my-nodejs-app:latest 484907488753.dkr.ecr.us-east-1.amazonaws.com/repositorykr/my-nodejs-app:latest
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 484907488753.dkr.ecr.us-east-1.amazonaws.com
      - docker push 484907488753.dkr.ecr.us-east-1.amazonaws.com/repositorykr:latest
